Repository bone-stew/popmate-be, pull requests merged in 2023-10, with the labels that each got.

#195 fix: 예약자 관련 API 버그 수정
  src/docs/asciidoc/reservation.adoc
  src/main/java/com/bonestew/popmate/reservation/application/ReservationEventService.java
  src/main/java/com/bonestew/popmate/reservation/application/ReservationInformationService.java
  src/main/java/com/bonestew/popmate/reservation/exception/UserReservationNotFoundException.java
  src/main/java/com/bonestew/popmate/reservation/persistence/UserReservationDao.java
  src/main/java/com/bonestew/popmate/reservation/presentation/ReservationEventController.java
  src/main/java/com/bonestew/popmate/reservation/presentation/ReservationInformationController.java
  src/main/java/com/bonestew/popmate/reservation/presentation/dto/CreateUserReservationResponse.java
  src/main/java/com/bonestew/popmate/reservation/presentation/dto/ReservationEntranceResponse.java
  src/main/java/com/bonestew/popmate/reservation/presentation/dto/ReservationResponse.java
  src/main/resources/mapper/reservation/UserReservationMapper.xml
  src/test/java/com/bonestew/popmate/reservation/presentation/ReservationEventControllerTest.java
  src/test/java/com/bonestew/popmate/reservation/presentation/ReservationInformationControllerTest.java
Labels: enhancement

#203 fix: 예약 목록 정렬, 예약 수정 비즈니스 로직 추가
  src/main/java/com/bonestew/popmate/popupstore/application/PopupStoreService.java
  src/main/java/com/bonestew/popmate/reservation/application/ReservationEventService.java
  src/main/java/com/bonestew/popmate/reservation/application/dto/CreateReservationDto.java
  src/main/java/com/bonestew/popmate/reservation/persistence/ReservationDao.java
  src/main/resources/mapper/reservation/ReservationMapper.xml
  src/main/resources/mapper/reservation/UserReservationMapper.xml
Labels: bug

#206 fix: 팝업스토어 검색 쿼리 생성 날짜 수정
  src/main/resources/mapper/popupstore/PopupStoreMapper.xml
Labels: bug

#205 feat: 선착순 예약 동시성 해결을 위한 분산락 구현
  build.gradle
  src/main/java/com/bonestew/popmate/PopmateApplication.java
  src/main/java/com/bonestew/popmate/annotation/DistributedLock.java
  src/main/java/com/bonestew/popmate/aspect/DistributedLockAspect.java
  src/main/java/com/bonestew/popmate/config/RedissonConfig.java
  src/main/java/com/bonestew/popmate/parser/CustomSpELParser.java
  src/main/java/com/bonestew/popmate/reservation/application/ReservationEventService.java
  src/test/resources/application.yml
Labels: enhancement

#207 chore: 로컬 환경 redis 변경
  src/main/java/com/bonestew/popmate/config/EmbeddedRedisConfig.java
  src/main/resources/application-local.yml
Labels: enhancement

#208 chore: elasticache 설정 및 배포용 properties 변경
  Dockerfile
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: deploy

#212 docs: Update README.md
  README.md
Labels: documentation

#224 fix: 예약 인원 수 변경 쿼리 수정
  src/main/java/com/bonestew/popmate/reservation/application/ReservationInformationService.java
  src/main/java/com/bonestew/popmate/reservation/persistence/ReservationDao.java
  src/main/resources/mapper/reservation/ReservationMapper.xml
Labels: bug

#225 docs: Update adoc, README.md
  README.md
  src/docs/asciidoc/chart.adoc
  src/docs/asciidoc/chat.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/order.adoc
  src/docs/asciidoc/popup-store.adoc
  src/test/java/com/bonestew/popmate/order/presentation/OrderControllerTest.java
Labels: documentation
